### ISSUE TITLE
Add a tool to concatenate datasets

### ISSUE THREAD

**Issue by jnothman** [Weed-AI/Weed-AI#11]
Not sure how useful this is in practice, but might be a good exercise to demonstrate the structure of the objects, and demonstrate pointer swizzling/unswizzling.

**Comment by hlydecker** [comment]
I've been looking into the COCO-Assistant dataset utility functions for some inspiration: https://github.com/ashnair1/COCO-Assistant/blob/master/coco_assistant/coco_assistant.py

One of the key features of COCO-Assistant is that a specific directory structure is adhered to.
