### ISSUE TITLE
Distinguish between different plant parts in annotations

### ISSUE THREAD

**Issue by jnothman** [Weed-AI/Weed-AI#119]
For bounding box and instance annotations, we might need to distinguish between annotations bounding the whole part of the plant vs an identifiable portion of the plant.
@geezacoleman suggests:
>  we would need to define on a whole-dataset level the part of the plant that is the target of the annotation, but also on a per class basis e.g.:
> * Whole plant
> * Leaves
> * Stem/tiller
> * Growing point
> * Flowers
> * Seed pods (this could crossover neatly with the wheat ear data that the other groups in the TCG are using)

I suggested that

> This kind of subdivision could be a qualifier to the annotation category.

That is, we would distinguish between "weed: <species> (stem)" and "weed: <species> (flower)".

I think "any part" might be clearer than "whole plant" btw.

**Comment by geezacoleman** [comment]
> That is, we would distinguish between "weed: (stem)" and "weed: (flower)".

As long as both the 'weed' part and the '<plant part>' are searchable this would be ok. People should be able to either use all annotations grouped for a weed species (i.e. not care about specificity of the annotation) or potentially filter by plant part? The latter would be a much more niche use case and might not necessarily be worthwhile in the first version of this.

@jnothman mentioned:
> Could we make fewer subcategories than the below? Would we ever label the leaves without the stem? 

I have done leaf and flower-only annotation before. Annotating leaves is potentially one method for managing whole plant occlusion. In some instances, only one leaf might be visible of the weed. Stem is less so, but is still an interesting area of research for very precise detection. Leaf, flower, stem would be important and wheat head datasets already exist, so it makes sense to include seed/seed pods etc.

E.g. [Lottes et al. 2020](https://arxiv.org/abs/1806.03413):
>Compared to state-of-the-art approaches, our approach not only substantially improves the stem detection accuracy, i.e., distinguishing crop and weed stems, but also provides an improvement in the semantic segmentation performance.

**Comment by jnothman** [comment]
See #574
