### ISSUE TITLE
Category mapping editor

### ISSUE THREAD

**Issue by hlydecker** [Weed-AI/Weed-AI#152]
In a future implementation where we enable users to upload non-weedcoco datasets, we could include a tool to generate the category mapping file. This is particularly important for VOC and non-COCO segmentation datasets.

Likely will build off learnings from #146 #151 #148

**Comment by jnothman** [comment]
This will probably allow for entering / mapping from EPPO codes too....

**Comment by jnothman** [comment]
I'm not sure about the idea of a standalone category mapping tool, but within the uploader, we might want a step like the following:

![image](https://user-images.githubusercontent.com/78827/116636541-e2d0d680-a9a4-11eb-9ea0-9b28009a5223.png)


This would apply to coco, voc, labelbox, etc. (For selecting a role, I don't care whether we use radio buttons as presented, a drop down, or tabs as we're using in the agcontext editor.)

For segmentation, where category is indicated by colour we might need something more like:

![image](https://user-images.githubusercontent.com/78827/116636754-67235980-a9a5-11eb-9b51-78d4d040fbdf.png)

We would also need the option of labelling the category as "background" (i.e. delete segmentations of this colour)

**Comment by ElevnLi** [comment]
For the first example, does this step just convert
```json
"categories": [
        {
            "id": 0,
            "name": "wheat"
        },
        {
            "id": 1,
            "name": "wild radish"
        },
        {
            "id": 2,
            "name": "ryegrass"
        }
    ],
```
to
```json
"categories": [
        {
            "id": 0,
            "name": "crop: wheat"
        },
        {
            "id": 1,
            "name": "weed: wild radish"
        },
        {
            "id": 2,
            "name": "weed: ryegrass"
        }
    ],
```

**Comment by jnothman** [comment]
The user would have to fill in the form, e.g. 
![image](https://user-images.githubusercontent.com/78827/116647056-fb4ceb00-a9bc-11eb-8800-daec49c2bbdf.png)

Should probably add to the form [enter scientific name]
