### ISSUE TITLE
Search results summary 

### ISSUE THREAD

**Issue by hlydecker** [Weed-AI/Weed-AI#28]
When searching, users should see a paginated list of images with masks shown, as well as some basic summary details like crop and weed species.

**Comment by jnothman** [comment]
Maybe also tagged with task types they'd support?

**Comment by jnothman** [comment]
Maybe also something related to location or soil type???

**Comment by jnothman** [comment]
And growth stage?

No, maybe just leave that in the faceting.

**Comment by jnothman** [comment]
We probably need a bit more detail here for demo. Currently it's showing the crop species taken from agcontext, but not weed species?

**Comment by jnothman** [comment]
Related, similar: #100
