### ISSUE TITLE
weedcoco bbox annotation missing annotation dict keys like 'segmentation'

### ISSUE THREAD

**Issue by geezacoleman** [Weed-AI/Weed-AI#287]
Currently working on visualising the conversions to check if they are accurate and came across a ` raise Exception('datasetType not supported')` error. Did a bit more diving and found the original COCO has the following annotation keys:
`annotation{
"id": int,
"image_id": int,
"category_id": int,
"segmentation": RLE or [polygon],
"area": float,
"bbox": [x,y,width,height],
"iscrowd": 0 or 1,}`

Weedcoco only has:
`{
            "id": 76,
            "image_id": 19,
            "category_id": 0,
            "bbox": [ ]
        },`

Is this by design? I can change the converter to include the additional segmentation, area, isCrowd etc. if needed? It currently doesn't work with pycocotools otherwise.

**Comment by jnothman** [comment]
I'll need a bit more clarity on how to reproduce the error. Happy to have a video call where you can show me your screen etc.

**Comment by jnothman** [comment]
Ahh, I see the code in pycocotools now: http://robolab.cse.unsw.edu.au:4443/hri-edu-au/cocoapi/-/blob/1b97cbf79cad503a968b5a43e99b2a7e9678ed26/PythonAPI/pycocotools/coco.py#L246.

This is because, it seems, pycocotools does not support bounding box-only instances.

**Comment by jnothman** [comment]
Should we set `"segmentation": []` on datasets with bbox but no segmentation? This would enable their use with pycocotools. (I'd rather pycocotools get fixed, but it looks poorly maintained.)
