### ISSUE TITLE
SEO: home page needs a description

### ISSUE THREAD

**Issue by jnothman** [Weed-AI/Weed-AI#361]
This isn't cool:
![image](https://user-images.githubusercontent.com/78827/111260716-6f356d00-8675-11eb-82ff-5c827ff26760.png)

**Comment by jnothman** [comment]
In an effort to resolve this, I think we can put put something on the home page by way of introduction.

WDYT of the following, @ElevnLi, @geezacoleman?

![image](https://user-images.githubusercontent.com/78827/111401573-a3646880-871d-11eb-895a-42e8aea27e8a.png)

**Comment by geezacoleman** [comment]
That looks good Joel!

**Comment by jnothman** [comment]
Fixed
