### ISSUE TITLE
File size too big error

### ISSUE THREAD

**Issue by geezacoleman** [Weed-AI/Weed-AI#482]
The errors are nice and explanatory! Any chance we could increase accepted image size limit a touch? These images from an iPhone XS in 2019 are ~10.9MB or are there downstream consequences of doing so?

**Comment by geezacoleman** [comment]
Once I removed EXIF data it actually uploaded fine, but I guess the question remains it seems 10MB is probably at the boundary of file sizes. Is it possible to go slightly larger?

**Comment by jnothman** [comment]
If this is an appropriate file size, I'm sure we can accept it... and suffer the consequences when we run out of disk space!

**Comment by geezacoleman** [comment]
I think if we increase it to 15MB it should most images from phones hopefully (barring the 100 MP S21 Ultra max pro etc. photos). I don't think we'll have an issue for machine vision cameras.
