### ISSUE TITLE
Lines across image zoom preview

### ISSUE THREAD

**Issue by geezacoleman** [Weed-AI/Weed-AI#518]
Lines seem to appear in certain parts of the preview as you move around. Not a major issue but thought I'd track it here.

![image](https://user-images.githubusercontent.com/51358498/123866112-4e2a1c80-d8f2-11eb-96f6-708026cbd1ba.png)

**Comment by jnothman** [comment]
Strange. Might be dependent on browser etc. What setup are you using? The magnification feature (and the new bounding box display) is somewhat experimental and maybe should be left off given that we have no time to improve them
________________________________
From: Guy Coleman ***@***.***>
Sent: Wednesday, June 30, 2021 6:55:17 AM
To: Sydney-Informatics-Hub/Weed-AI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Sydney-Informatics-Hub/Weed-AI] Lines across image zoom preview (#518)


Lines seem to appear in certain parts of the preview as you move around. Not a major issue but thought I'd track it here.

[image]<https://user-images.githubusercontent.com/51358498/123866112-4e2a1c80-d8f2-11eb-96f6-708026cbd1ba.png>

**Comment by geezacoleman** [comment]
I'm just using Chrome, haven't tried anything else yet, though the feature works on my phone too (albeit a bit awkwardly).

**Comment by jnothman** [comment]
Yeah, I’ve noticed on mobile screens the bounding boxes are misplaced.

**Comment by jnothman** [comment]
Preview disabled
