### ISSUE TITLE
Improve uploading of large zip files by chunking

### ISSUE THREAD

**Issue by jnothman** [Weed-AI/Weed-AI#584]

**Comment by spikelynch** [comment]
- [ ] fix Uppy height
- [ ] automatically start uploading when file selected
- [ ] remove "Done" button/bar at end of upload
- [ ] revert to djproxy
- [ ] test files > chunk size
- [ ] test that unzipping the files still works
- [ ] cypress test for zip uploading

**Comment by spikelynch** [comment]
Have got a basic cypress test for the zip uploader working, but want to talk about the right way to handle test fixtures as I don't really want to put a 13Mb zipfile into the repo

**Comment by jnothman** [comment]
The purpose of the test is to avoid regressions in how we incorporate Uppy in UI, and in how we interface with tusd in the backend. A success, even on a small file, requires several reqs/resps between frontend and tusd. I don't think we therefore need to test the chunking protocol (and if we do we could set an unrealistically small chunk size). As such, I don't see why we shouldn't just use a small, single-image zip file.

**Comment by spikelynch** [comment]
ok no worries, will make one.
