### ISSUE TITLE
cvat task drop-down is not working if there are 10+ tasks

### ISSUE THREAD

**Issue by spikelynch** [Weed-AI/Weed-AI#620]

**Comment by spikelynch** [comment]
This only showed up because I was running the tests repeatedly on my laptop and tasks were building up. It won't show up in CI unless we write a test which creates 10 tasks.

Also: the test is creating these tasks as a different user each time, so I don't know why the API call which the drop-down component is making isn't just returning one test for the current user.

**Comment by ElevnLi** [comment]
[This commit](https://github.com/Weed-AI/Weed-AI/commit/8d73031d875b2eed933a467b131c0f707a429e32) was to fix that
