### ISSUE TITLE
annotate tab doesn't appear on 'About' page

### ISSUE THREAD

**Issue by geezacoleman** [Weed-AI/Weed-AI#699]
It appears when you're on all other pages but not on About
![image](https://user-images.githubusercontent.com/51358498/186091893-500435aa-bf90-41b2-a268-2701b44ababd.png)

![image](https://user-images.githubusercontent.com/51358498/186091938-6207732e-c38e-44e5-923e-6495b588eee1.png)

**Comment by hvidy** [comment]
I'm unable to duplicate this issue. Might have been caused by a cached version of the 'About' page from before the addition of the annotate tab.
![image](https://user-images.githubusercontent.com/16135394/192171283-35852705-261b-46de-8c4b-350a7d016f57.png)
